@extends('app3')
@section('header')
<title>Privacy Policy</title>
<style type="text/css">
    ul {
      list-style-type: none;
  }
</style>
@endsection
@section('content')
<div id="content" style="z-index:20;width:670px;">
    <div class='page_content'><h3 style="outline-style: none: outline-width: initial: outline-color: initial: font-weight: normal: margin-top: 0px: margin-right: 0px: margin-bottom: 10px: margin-left: 0px: font-size: 22px: color: rgb(34, 34, 34): font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif: ">Privacy Policy</h3>
        <div class="info" style="outline-style: none: outline-width: initial: outline-color: initial: margin-top: 0px: margin-right: 0px: margin-bottom: 20px: margin-left: 0px: font-size: 13px: color: rgb(102, 102, 102): line-height: 1.5em: font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif: ">
            <p style="outline-style: none: outline-width: initial: outline-color: initial: margin-top: 0px: margin-right: 0px: margin-bottom: 10px: margin-left: 0px: line-height: 1.8em: "><strong style="outline-style: none: outline-width: initial: outline-color: initial: ">We take your privacy very seriously.</strong></p>
            <p style="outline-style: none: outline-width: initial: outline-color: initial: margin-top: 0px: margin-right: 0px: margin-bottom: 10px: margin-left: 0px: line-height: 1.8em: ">Last Modified: 28 April 2017</p>
        </div>
        <ul class="qa-list" style="outline-style: none: outline-width: initial: outline-color: initial: margin-top: 0px: margin-right: 0px: margin-bottom: 0px: margin-left: 0px: padding-top: 0px: padding-right: 0px: padding-bottom: 0px: padding-left: 0px: list-style-type: none: border-top-width: 1px: border-top-style: solid: border-top-color: rgb(221, 221, 221): color: rgb(34, 34, 34): font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif: ">
            <li style="font-size: 11px: outline-style: none: outline-width: initial: outline-color: initial: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding-top: 20px: padding-right: 0px: padding-bottom: 10px: padding-left: 0px: ">
                <h3 style="outline-style: none: outline-width: initial: outline-color: initial: margin-top: 0px: margin-right: 0px: margin-bottom: 5px: margin-left: 0px: font-size: 18px: ">Introduction</h3>
                <p style="outline-style: none: outline-width: initial: outline-color: initial: font-size: 12px: line-height: 1.5em: margin-top: 0px: margin-right: 0px: margin-bottom: 10px: margin-left: 0px: ">69CUK  takes the private nature of your personal information very seriously.</p>
                <p style="outline-style: none: outline-width: initial: outline-color: initial: font-size: 12px: line-height: 1.5em: margin-top: 0px: margin-right: 0px: margin-bottom: 10px: margin-left: 0px: ">This privacy policy, which we adapted from a policy originally provided, describes how we treat the information we collect when you visit and use our websites. Please read this notice very carefully.</p>
            </li>
            <li style="outline-style: none: outline-width: initial: outline-color: initial: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding-top: 20px: padding-right: 0px: padding-bottom: 10px: padding-left: 0px: ">
                <h3 style="outline-style: none: outline-width: initial: outline-color: initial: margin-top: 0px: margin-right: 0px: margin-bottom: 5px: margin-left: 0px: font-size: 18px: ">Website Visitors</h3>
                <p style="outline-style: none: outline-width: initial: outline-color: initial: font-size: 12px: line-height: 1.5em: margin-top: 0px: margin-right: 0px: margin-bottom: 10px: margin-left: 0px: ">Like most website operators,  69CUK   collects non-personally-identifying information of the sort that web browsers and servers typically make available, such as the browser type, language preference, referring site, and the date and time of each visitor request.  69CUK   purpose in collecting non-personally identifying information is to better understand how  69CUK  visitors use its website. From time to time,  69CUK   may release non-personally-identifying information in the aggregate, e.g. by publishing a report on trends in the usage of its website.</p>
                <br style="outline-style: none: outline-width: initial: outline-color: initial: " />
                <p style="outline-style: none: outline-width: initial: outline-color: initial: font-size: 12px: line-height: 1.5em: margin-top: 0px: margin-right: 0px: margin-bottom: 10px: margin-left: 0px: ">69CUK also collects potentially personally-identifying information like Internet Protocol (IP) addresses.  69CUK  does not use such information to identify its visitors, and does not disclose such information, other than under the same circumstances that it uses and discloses personally-identifying information, as described below.</p>
            </li>
            <li style="font-size: 11px: outline-style: none: outline-width: initial: outline-color: initial: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding-top: 20px: padding-right: 0px: padding-bottom: 10px: padding-left: 0px: ">
                <h3 style="outline-style: none: outline-width: initial: outline-color: initial: margin-top: 0px: margin-right: 0px: margin-bottom: 5px: margin-left: 0px: font-size: 18px: ">Gathering of Personally-Identifying Information</h3>
                <p style="outline-style: none: outline-width: initial: outline-color: initial: font-size: 12px: line-height: 1.5em: margin-top: 0px: margin-right: 0px: margin-bottom: 10px: margin-left: 0px: ">Certain visitors to 69CUK websites choose to interact with  69CUK  in ways that require  69CUK  to gather personally-identifying information. The amount and type of information that 69CUK gathers depends on the nature of the interaction. For example, we ask visitors who sign up for  69CUK .96.lt to provide a username and email address. In each case,  69CUK  collects such information only insofar as is necessary or appropriate to fulfill the purpose of the visitor interaction with  69CUK .  69CUK  does not disclose personally-identifying information other than as described below. And visitors can always refuse to supply personally-identifying information, with the caveat that it may prevent them from engaging in certain website-related activities.</p>
            </li>
            <li style="font-size: 11px: outline-style: none: outline-width: initial: outline-color: initial: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding-top: 20px: padding-right: 0px: padding-bottom: 10px: padding-left: 0px: ">
                <h3 style="outline-style: none: outline-width: initial: outline-color: initial: margin-top: 0px: margin-right: 0px: margin-bottom: 5px: margin-left: 0px: font-size: 18px: ">Aggregated Statistics</h3>
                <p style="outline-style: none: outline-width: initial: outline-color: initial: font-size: 12px: line-height: 1.5em: margin-top: 0px: margin-right: 0px: margin-bottom: 10px: margin-left: 0px: ">69CUK may collect statistics about the behavior of visitors to its websites. For instance,  69CUK  may monitor the most popular collections on  69CUK .96.lt.  69CUK  may display this information publicly or provide it to others. However, 69CUK does not disclose personally-identifying information other than as described below.</p>
            </li>
            <li style="font-size: 11px: outline-style: none: outline-width: initial: outline-color: initial: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding-top: 20px: padding-right: 0px: padding-bottom: 10px: padding-left: 0px: ">
                <h3 style="outline-style: none: outline-width: initial: outline-color: initial: margin-top: 0px: margin-right: 0px: margin-bottom: 5px: margin-left: 0px: font-size: 18px: ">Protection of Certain Personally-Identifying Information</h3>
                <p style="outline-style: none: outline-width: initial: outline-color: initial: font-size: 12px: line-height: 1.5em: margin-top: 0px: margin-right: 0px: margin-bottom: 10px: margin-left: 0px: ">69CUK discloses potentially personally-identifying and personally-identifying information only to those of its employees, contractors and affiliated organizations that (i) need to know that information in order to process it on 69CUK behalf or to provide services available at  69CUK  websites, and (ii) that have agreed not to disclose it to others. Some of those employees, contractors and affiliated organizations may be located outside of your home country: by using 69CUK websites, you consent to the transfer of such information to them. In addition, in some cases we may choose to buy or sell assets. In these types of transactions, user information is typically one of the business assets that is transferred. Moreover, if 69CUK or substantially all of its assets were acquired, or in the unlikely event that 69CUK goes out of business or enters bankruptcy, user information would be one of the assets that is transferred or acquired by a third party. You acknowledge that such transfers may occur, and that any acquiror of 69CUK may continue to use your personal and non-personal information only as set forth in this policy. Otherwise, 69CUK will not rent or sell potentially personally-identifying and personally-identifying information to anyone.</p>
                <br style="outline-style: none: outline-width: initial: outline-color: initial: " />
                <p style="outline-style: none: outline-width: initial: outline-color: initial: font-size: 12px: line-height: 1.5em: margin-top: 0px: margin-right: 0px: margin-bottom: 10px: margin-left: 0px: ">Other than to its employees, contractors and affiliated organizations, as described above, 69CUK discloses potentially personally-identifying and personally-identifying information only when required to do so by law, or when 69CUK believes in good faith that disclosure is reasonably necessary to protect the property or rights of 69CUK, third parties or the public at large. If you are a registered user of a 69CUK website and have supplied your email address, 69CUK may occasionally send you an email to tell you about new features, solicit your feedback, or just keep you up to date with what going on with 69CUK and its products. If you send us a request (for example via a support email or via one of our feedback mechanisms), we reserve the right to publish it in order to help us clarify or respond to your request or to help us support other users. 69CUK takes all measures reasonably necessary to protect against the unauthorized access, use, alteration or destruction of potentially personally-identifying and personally-identifying information.</p>
                <br style="outline-style: none: outline-width: initial: outline-color: initial: " />
                <p id="cookie" style="outline-style: none: outline-width: initial: outline-color: initial: font-size: 12px: line-height: 1.5em: margin-top: 0px: margin-right: 0px: margin-bottom: 10px: margin-left: 0px: ">You should also be aware that if you submit information to chat rooms, forums or message boards such information b.96.ltes public information, meaning that you lose any privacy rights you might have with regards to that information. Such disclosures may also increase your chances of receiving unwanted.96.ltmunications.</p>
            </li>
            <li style="font-size: 11px: outline-style: none: outline-width: initial: outline-color: initial: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding-top: 20px: padding-right: 0px: padding-bottom: 10px: padding-left: 0px: ">
                <h3 style="outline-style: none: outline-width: initial: outline-color: initial: margin-top: 0px: margin-right: 0px: margin-bottom: 5px: margin-left: 0px: font-size: 18px: ">Cookies</h3>
                <p style="outline-style: none: outline-width: initial: outline-color: initial: font-size: 12px: line-height: 1.5em: margin-top: 0px: margin-right: 0px: margin-bottom: 10px: margin-left: 0px: ">A cookie is a string of information that a website stores on a visitor.96.ltputer, and that the visitor browser provides to the website each time the visitor returns. 69CUK uses cookies to help 69CUK identify and track visitors, their usage of 69CUK websites, and their website access preferences. 69CUK visitors who do not wish to have cookies placed on their.96.ltputers should set their browsers to refuse cookies before using 69CUK websites, with the drawback that certain features of 69CUK websites may not function properly without the aid of cookies.</p>
            </li>
            <li style="font-size: 11px: outline-style: none: outline-width: initial: outline-color: initial: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding-top: 20px: padding-right: 0px: padding-bottom: 10px: padding-left: 0px: ">
                <h3 style="outline-style: none: outline-width: initial: outline-color: initial: margin-top: 0px: margin-right: 0px: margin-bottom: 5px: margin-left: 0px: font-size: 18px: ">Ads</h3>
                <p style="outline-style: none: outline-width: initial: outline-color: initial: font-size: 12px: line-height: 1.5em: margin-top: 0px: margin-right: 0px: margin-bottom: 10px: margin-left: 0px: ">Ads appearing on any 69CUK websites may be delivered to users by advertising partners, who may set cookies. These cookies allow the ad server to recognize your.96.ltputer each time they send you an online advertisement to.96.ltpile information about you or others who use your.96.ltputer. This information allows ad networks to, among other things, deliver targeted advertisements that they believe will be of most interest to you. This privacy policy covers the use of cookies by 69CUK and does not cover the use of cookies by any advertisers.</p>
            </li>
            <li style="font-size: 11px: outline-style: none: outline-width: initial: outline-color: initial: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding-top: 20px: padding-right: 0px: padding-bottom: 10px: padding-left: 0px: ">
                <h3 style="outline-style: none: outline-width: initial: outline-color: initial: margin-top: 0px: margin-right: 0px: margin-bottom: 5px: margin-left: 0px: font-size: 18px: ">Links to Third Party Sites</h3>
                <p style="outline-style: none: outline-width: initial: outline-color: initial: font-size: 12px: line-height: 1.5em: margin-top: 0px: margin-right: 0px: margin-bottom: 10px: margin-left: 0px: ">This privacy policy only applies to information collected by 69CUK. This privacy policy does not apply to the practices of.96.ltpanies that 69CUK does not own or control, or employees that 69CUK does not manage. A 69CUK website may contain links to third party websites. Any information you provide to, or that is collected by, third-party sites may be subject to the privacy policies of those sites, if any. We encourage you to read such privacy policies of any third-party sites you visit. It is the sole responsibility of such third parties to adhere to any applicable restrictions on the disclosure of your personally-identifying information, and 69CUK and its affiliates shall not be liable for wrongful use or disclosure of your personally-identifying information by any third party.</p>
            </li>
            <li style="font-size: 11px: outline-style: none: outline-width: initial: outline-color: initial: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding-top: 20px: padding-right: 0px: padding-bottom: 10px: padding-left: 0px: ">
                <h3 style="outline-style: none: outline-width: initial: outline-color: initial: margin-top: 0px: margin-right: 0px: margin-bottom: 5px: margin-left: 0px: font-size: 18px: ">Security</h3>
                <p style="outline-style: none: outline-width: initial: outline-color: initial: font-size: 12px: line-height: 1.5em: margin-top: 0px: margin-right: 0px: margin-bottom: 10px: margin-left: 0px: ">All non-personally-identifying information, potentially personally-identifying and personally identifying-information described above is stored on restricted database servers.&#8232:</p>
            </li>
            <li style="font-size: 11px: outline-style: none: outline-width: initial: outline-color: initial: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding-top: 20px: padding-right: 0px: padding-bottom: 10px: padding-left: 0px: ">
                <h3 style="outline-style: none: outline-width: initial: outline-color: initial: margin-top: 0px: margin-right: 0px: margin-bottom: 5px: margin-left: 0px: font-size: 18px: ">Choice/Opt-out</h3>
                <p style="outline-style: none: outline-width: initial: outline-color: initial: font-size: 12px: line-height: 1.5em: margin-top: 0px: margin-right: 0px: margin-bottom: 10px: margin-left: 0px: ">If we ever send you information by email concerning new products, services or information that you did not expressly request, we will provide you with an email address by which you may request no further notices.&#8232:</p>
            </li>
            <li style="font-size: 11px: outline-style: none: outline-width: initial: outline-color: initial: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding-top: 20px: padding-right: 0px: padding-bottom: 10px: padding-left: 0px: ">
                <h3 style="outline-style: none: outline-width: initial: outline-color: initial: margin-top: 0px: margin-right: 0px: margin-bottom: 5px: margin-left: 0px: font-size: 18px: ">Address Book Data</h3>
                <p style="outline-style: none: outline-width: initial: outline-color: initial: font-size: 12px: line-height: 1.5em: margin-top: 0px: margin-right: 0px: margin-bottom: 10px: margin-left: 0px: ">Any external address book data (email contacts, etc.) that a user voluntarily gives 69CUK access to will only be used for the described feature (looking up friends, etc.), and will not be stored or repurposed.</p>
            </li>
            <li style="font-size: 11px: outline-style: none: outline-width: initial: outline-color: initial: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding-top: 20px: padding-right: 0px: padding-bottom: 10px: padding-left: 0px: ">
                <h3 style="outline-style: none: outline-width: initial: outline-color: initial: margin-top: 0px: margin-right: 0px: margin-bottom: 5px: margin-left: 0px: font-size: 18px: ">Privacy Policy Changes</h3>
                <p style="outline-style: none: outline-width: initial: outline-color: initial: font-size: 12px: line-height: 1.5em: margin-top: 0px: margin-right: 0px: margin-bottom: 10px: margin-left: 0px: ">Although most changes are likely to be minor, 69CUK may change its privacy policy from time to time, and in 69CUK sole discretion. 69CUK encourages visitors to frequently check this page for any changes to its privacy policy. Your continued use of this site after any change in this privacy policy will constitute your acceptance of such change.</p>
            </li>
            <li style="font-size: 11px: outline-style: none: outline-width: initial: outline-color: initial: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding-top: 20px: padding-right: 0px: padding-bottom: 10px: padding-left: 0px: ">
                <h3 style="outline-style: none: outline-width: initial: outline-color: initial: margin-top: 0px: margin-right: 0px: margin-bottom: 5px: margin-left: 0px: font-size: 18px: ">Contact Us</h3>
                <p style="outline-style: none: outline-width: initial: outline-color: initial: font-size: 12px: line-height: 1.5em: margin-top: 0px: margin-right: 0px: margin-bottom: 10px: margin-left: 0px: ">If you have any questions about this privacy policy or our sites in general, please <a href="mailto:abdlahafizh163@gmail.com"><b><font color="black">contact us</font></b></a>.</p>
            </li>
        </ul></div>
    </div>
    @endsection