@extends('app3')
@section('header')
<title>Terms of Service</title>
<style type="text/css">
    ul {
      list-style-type: none;
  }
</style>
@endsection
@section('content')
<div id="content" style="z-index:20;width:670px;"> 
    <h3>Terms of Service</h3><p></p> <div class="info" style="outline: none: margin: 0px 0px 20px: font-size: 13px: color: rgb(102, 102, 102): line-height: 1.5em: font-family: Helvetica Neue, Helvetica, Arial, sans-serif: ">
    <p style="outline: none: margin: 0px 0px 10px: line-height: 1.8em: "><strong style="outline: none: ">Please read the following terms carefully before using 69CUK.</strong></p>
    <p style="outline: none: margin: 0px 0px 10px: line-height: 1.8em: ">Last Modified: 28 April 2017</p>
</div>
<ul class="qa-list" style="outline: none: margin: 0px: padding: 0px: list-style-type: none: border-top-width: 1px: border-top-style: solid: border-top-color: rgb(221, 221, 221): color: rgb(34, 34, 34): font-family: Helvetica Neue, Helvetica, Arial, sans-serif: font-size: 11px: ">
    <li style="outline: none: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding: 20px 0px 10px: ">
        <h3 style="outline: none: margin: 0px 0px 5px: font-size: 18px: ">Accepting the Terms of Service</h3>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">The purpose of this website,<a href="http://69CUK.96.lt/" style="outline: none: color: rgb(0, 165, 240): text-decoration: none: -webkit-transition: color 0.2s linear: ">69CUK.96.lt</a>(the Site), is to provide web publishing services. Please read these terms of service (Agreement) carefully before using the Site or any services provided on the Site (collectively, Services). By using or accessing the Services, you agree to b.96.lte bound by all the terms and conditions of this Agreement. If you do not agree to all the terms and conditions of this Agreement, do not use the Services. The Services are accessed by You (Subscriber or You) under the following terms and conditions:</p>
    </li>
    <li style="outline: none: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding: 20px 0px 10px: ">
        <h3 style="outline: none: margin: 0px 0px 5px: font-size: 18px: ">1. Access to the Services</h3>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">Subject to the terms and conditions of this Agreement, 69CUK, Inc may offer to provide the Services, as described more fully on the Site, and which are selected by Subscriber, solely for Subscriber own use, and not for the use or benefit of any third party. Services shall include, but not be limited to, any services 69CUK, Inc performs for Subscriber, as well as the offering of any Content (as defined below) on the Site. 69CUK, Inc may change, suspend or discontinue the Services at any time, including the availability of any feature, database, or Content. 69CUK, Inc may also impose limits on certain features and services or restrict Subscriber access to parts or all of the Services without notice or liability. 69CUK, Inc reserves the right, at its discretion, to modify these Terms of Service at any time by posting revised Terms of Service on the Site and by providing notice via e-mail, where possible, or on the Site. Subscriber shall be responsible for reviewing and b.96.lting familiar with any such modifications. Use of the Services by Subscriber following such modification constitutes Subscribers acceptance of the terms and conditions of this Agreement as modified.</p>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">Subscriber certifies to 69CUK, Inc that if Subscriber is an individual (i.e., not a corporate entity), Subscriber is at least 13 years of age. No one under the age of 13 may provide any personal information to or on 69CUK, Inc (including, for example, a name, address, telephone number or email address). Subscriber also certifies that it is legally permitted to use the Services and access the Site, and takes full responsibility for the selection and use of the Services and access of the Site. This Agreement is void where prohibited by law, and the right to access the Site is revoked in such jurisdictions.</p>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">69CUK, Inc will use reasonable efforts to ensure that the Site and Services are available twenty-four hours a day, seven days a week. However, there will be occasions when the Site and/or Services will be interrupted for maintenance, upgrades and repairs or due to failure of tel.96.ltmunications links and equipment. Every reasonable step will be taken by 69CUK, Inc to minimize such disruption where it is within 69CUK, Inc reasonable control.</p>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">You agree that neither 69CUK, Inc nor the Site will be liable in any event to you or any other party for any suspension, modification, discontinuance or lack of availability of the Site, the service, your Subscriber Content or other Content.</p>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">69CUK, Inc retains the right to create limits on use and storage in its sole discretion at any time with or without notice.</p>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">Subscriber shall be responsible for obtaining and maintaining any equipment or ancillary services needed to connect to, access the Site or otherwise use the Services, including, without limitation, modems, hardware, software, and long distance or local telephone service. Subscriber shall be responsible for ensuring that such equipment or ancillary services are.96.ltpatible with the Services.</p>
    </li>
    <li style="outline: none: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding: 20px 0px 10px: ">
        <h3 style="outline: none: margin: 0px 0px 5px: font-size: 18px: ">2. Site Content</h3>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">The Site and its contents are intended solely for the use of 69CUK, Inc Subscribers and may only be used in accordance with the terms of this Agreement. All materials displayed or performed on the Site, including, but not limited to text, graphics, logos, tools, photographs, images, illustrations, software or source code, audio and video, animations and Themes (as defined below), including without limitation the 69CUK, Inc Template Code (as defined below) (collectively, Content) (other than Content posted by Subscriber (Subscriber Content)) are the property of 69CUK, Inc and/or third parties and are protected . The 69CUK, Inc API shall be used solely pursuant to the terms of the API Terms of Service. All trademarks, service marks, and trade names are proprietary to 69CUK, Inc and/or third parties. Subscriber shall abide by all copyright notices, information, and restrictions contained in any Content accessed through the Services.</p>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">The Site is protected by copyright as a collective work and/or.96.ltpilation, international conventions, and other copyright laws. Other than as expressly set forth in this Agreement, Subscriber may not copy, modify, publish, transmit, upload, participate in the transfer or sale of, reproduce (except as provided in this Section), create derivative works based on, distribute, perform, display, or in any way exploit, any of the Content, software, materials, or Services in whole or in part.</p>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">Subscriber may download or copy the Content, and other items displayed on the Site for download, for personal use only, provided that Subscriber maintains all copyright and other notices contained in such Content. Downloading, copying, or storing any Content for other than personal, no.96.ltmercial use is expressly prohibited without prior written permission from 69CUK, Inc, or from the copyright holder identified in such Contents copyright notice. In the event You download software from the Site, the software, including any files, images incorporated in or generated by the software, and the data a.96.ltpanying the software (collectively, the Software) is licensed to You by 69CUK, Inc or third party licensors for Your personal, no.96.ltmercial use, and no title to the Software shall be transferred to You. You may own the Subscriber Content on which the Software is recorded, but 69CUK, Inc or third party licensors retain full and.96.ltplete title to the Software and all intellectual property rights therein.</p>
    </li>
    <li style="outline: none: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding: 20px 0px 10px: ">
        <h3 style="outline: none: margin: 0px 0px 5px: font-size: 18px: ">3. Subscriber Content</h3>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">Subscriber shall own all Subscriber Content that Subscriber contributes to the Site, but hereby grants and agrees to grant 69CUK, Inc a non-exclusive, worldwide, royalty-free, transferable right and license (with the right to sublicense), to use, copy, cache, publish, display, distribute, modify, create derivative works and store such Subscriber Content and to allow others to do so (Content License) in order to provide the Services. On termination of Subscriber membership to the Site and use of the Services, 69CUK, Inc shall make all reasonable efforts to promptly remove from the Site and cease use of the Subscriber Content: however, Subscriber recognizes and agrees that caching of or references to the Subscriber Content may not be immediately removed. Subscriber warrants, represents and agrees Subscriber has the right to grant 69CUK, Inc and the Site the rights set forth above. Subscriber represents, warrants and agrees that it will not contribute any Subscriber Content that (a) infringes, violates or otherwise interferes with any copyright or trademark of another party, (b) reveals any trade secret, unless Subscriber owns the trade secret or has the owner permission to post it, (c) infringes any intellectual property right of another or the privacy or publicity rights of another, (d) is libelous, defamatory, abusive, threatening, harassing, hateful, offensive or otherwise violates any law or right of any third party, (e) contains a virus, trojan horse, worm, time bomb or other.96.ltputer programming routine or engine that is intended to damage, detrimentally interfere with, surreptitiously intercept or expropriate any system, data or information, or (f) remains posted after Subscriber has been notified that such Subscriber Content violates any of sections (a) to (e) of this sentence. 69CUK, Inc reserves the right to remove any Subscriber Content from the Site, suspend or terminate Subscriber right to use the Services at any time, or pursue any other remedy or relief available to 69CUK, Inc and/or the Site under equity or law, for any reason (including, but not limited to, upon receipt of claims or allegations from third parties or authorities relating to such Subscriber Content or if 69CUK, Inc is concerned that Subscriber may have breached the immediately preceding sentence), or for no reason at all.</p>
    </li>
    <li style="outline: none: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding: 20px 0px 10px: ">
        <h3 style="outline: none: margin: 0px 0px 5px: font-size: 18px: ">4. Restrictions</h3>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">Subscriber is responsible for all of its activity in connection with the Services and accessing the Site. Any fraudulent, abusive, or otherwise illegal activity or any use of the Services or Content in violation of this Agreement may be grounds for termination of Subscriber right to Services or to access the Site. Subscriber may not post or transmit, or cause to be posted or transmitted, any.96.ltmunication or solicitation designed or intended to obtain password, account, or private information from any 69CUK, Inc user.</p>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">Use of the Site or Services to violate the security of any.96.ltputer network, crack passwords or security encryption codes, transfer or store illegal material including that are deemed threatening or obscene, or engage in any kind of illegal activity is expressly prohibited. Under no circumstances will Subscriber use the Site or the Service to (a) send unsolicited e-mails, bulk mail, spam or other materials to users of the Site or any other individual, (b) harass, threaten, stalk or abuse any person or party, including other users of the Site, (c) create a false identity or to impersonate another person, or (d) post any false, inaccurate or i.96.ltplete material or delete or revise any material that was not posted by You.</p>
    </li>
    <li style="outline: none: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding: 20px 0px 10px: ">
        <h3 style="outline: none: margin: 0px 0px 5px: font-size: 18px: ">5. Warranty disclaimer</h3>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">69CUK, Inc has no special relationship with or fiduciary duty to Subscriber. Subscriber acknowledges that 69CUK, Inc has no control over, and no duty to take any action regarding: which users gains access to the Site: which Content Subscriber accesses via the Site: what effects the Content may have on Subscriber: how Subscriber may interpret or use the Content: or what actions Subscriber may take as a result of having been exposed to the Content. Much of the Content of the Site is provided by and is the responsibility of the user or subscriber who posted the Content. 69CUK, Inc does not monitor the Content of the Site and takes no responsibility for such Content. Subscriber releases 69CUK, Inc from all liability for Subscriber having acquired or not acquired Content through the Site. The Site may contain, or direct Subscriber to sites containing, information that some people may find offensive or inappropriate. 69CUK, Inc makes no representations concerning any content contained in or accessed through the Site, and 69CUK, Inc will not be responsible or liable for the accuracy, copyright.96.ltpliance, legality or decency of material contained in or accessed through the Site.</p>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">Although 69CUK, Inc and the Site will make reasonable efforts to store and preserve the material residing on the Site, neither 69CUK, Inc nor the Site is responsible or liable in any way for the failure to store, preserve or access Subscriber Content or other materials you transmit or archive on the Site. You are strongly urged to take measures to preserve copies of any data, material, content or information you post or upload on the Site. You are solely responsible for creating back-ups of your Subscriber Content.</p>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">The Services, Content, Site and any Software are provided on an "as is" basis, without warranties of any kind, either express or implied, including, without limitation, implied warranties of merchantability, fitness for a particular purpose or non-infringement. 69CUK, Inc makes no representations or warranties of any kind with respect to the Site, the Services, including any representation or warranty that the use of the Site or Services will (a) be timely, uninterrupted or error-free or operate in.96.ltbination with any other hardware, software, system or data, (b) meet your requirements or expectations, (c) be free from errors or that defects will be corrected, (d) be free of viruses or other harmful.96.ltponents.</p>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">To the fullest extent allowed by law, 69CUK, Inc disclaims any liability or responsibility for the accuracy, reliability, availability,.96.ltpleteness, legality or operability of the material or services provided on this Site. By using this Site, you acknowledge that 69CUK, Inc is not responsible or liable for any harm resulting from (1) use of the Site: (2) downloading information contained on the Site including but not limited to downloads of content posted by subscribers: (3) unauthorized disclosure of images, information or data that results from the upload, download or storage of content posted by subscribers: (4) the temporary or permanent inability to access or retrieve any Subscriber Content from the Site, including, without limitation, harm caused by viruses, worms, trojan horses, or any similar contamination or destructive program.</p>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">Some places do not allow limitations on how long an implied warranty lasts, so the above limitations may not apply to Subscriber.</p>
    </li>
    <li style="outline: none: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding: 20px 0px 10px: ">
        <h3 style="outline: none: margin: 0px 0px 5px: font-size: 18px: ">6. Third party websites</h3>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">Users of the Site may gain access from the Site to third party sites on the Internet through hypertext or other.96.ltputer links on the Site. Third party sites are not within the supervision or control of 69CUK, Inc or the Site. Unless explicitly otherwise provided, neither 69CUK, Inc nor the Site make any representation or warranty whatsoever about any third party site that is linked to the Site, or endorse the products or services offered on such site. 69CUK, Inc and the Site disclaim: (a) all responsibility and liability for content on third party websites and (b) any representations or warranties as to the security of any information (including, without limitation, credit card and other personal information) You might be requested to give any third party, and You hereby irrevocably waive any claim against the Site or 69CUK, Inc with respect to such sites and third party content.</p>
    </li>
    <li style="outline: none: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding: 20px 0px 10px: ">
        <h3 style="outline: none: margin: 0px 0px 5px: font-size: 18px: ">7. Registration and security</h3>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">As a condition to using Services, Subscriber will be required to register with 69CUK, Inc and select a password and 69CUK, Inc URL. Subscriber shall provide 69CUK, Inc with accurate,.96.ltplete, and updated registration information, including Subscriber e-mail address. Failure to do so shall constitute a breach of this Agreement, which may result in immediate termination of Subscribers account. Subscriber may not (a) select or use as a 69CUK, Inc URL a name of another person with the intent to impersonate that person: or (b) use as a 69CUK, Inc URL a name subject to any rights of a person other than Subscriber without appropriate authorization. 69CUK, Inc reserves the right to refuse registration of, or cancel a 69CUK, Inc URL in its discretion. Subscriber shall be responsible for maintaining the confidentiality of Subscribers 69CUK, Inc password. Subscriber is solely responsible for any use of or action taken under Subscriber password and accepts full responsibility for all activity conducted through Subscriber account and agrees to and hereby releases the Site and 69CUK, Inc from any and all liability concerning such activity. Subscriber agrees to notify 69CUK, Inc immediately of any actual or suspected loss, theft, or unauthorized use of Subscriber account or password. The Site will take reasonably security precautions when using the internet, telephone or other means to transport date or other.96.ltmunications, but expressly disclaims any and all liability for the accessing of any such data.96.ltmunications by unauthorized persons or entities.</p>
    </li>
    <li style="outline: none: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding: 20px 0px 10px: ">
        <h3 style="outline: none: margin: 0px 0px 5px: font-size: 18px: ">8. Indemnity</h3>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">Subscriber will indemnify and hold 69CUK, Inc, its directors, officers and employees, harmless, including costs and attorneys fees, from any claim or demand made by any third party due to or arising out of Subscriber access to the Site, use of the Services, the violation of this Agreement by Subscriber, or the infringement by Subscriber, or any third party using the Subscribers account, of any intellectual property or other right of any person or entity.</p>
    </li>
    <li style="outline: none: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding: 20px 0px 10px: ">
        <h3 style="outline: none: margin: 0px 0px 5px: font-size: 18px: ">9. Limitation of liability</h3>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">In no event shall 69CUK, Inc, its directors, officers, shareholders, employees or members be liable with respect to the Site or the Services for (a) any indirect, incidental, punitive, or consequential damages of any kind whatsoever: (b) damages for loss of use, profits, data, images, Subscriber Content or other intangibles: (c) damages for unauthorized use, non-performance of the Site, errors or omissions: or (d) damages related to downloading or posting Content. 69CUK, Incs and the Sites collective liability under this agreement shall be limited to three hundred U.S. Dollars. Some places do not allow the exclusion or limitation of incidental or consequential damages, so the above limitations and exclusions may not apply to Subscriber.</p>
    </li>
    <li style="outline: none: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding: 20px 0px 10px: ">
        <h3 style="outline: none: margin: 0px 0px 5px: font-size: 18px: ">10. Fees and payment</h3>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">69CUK, Inc may change its prices at any time but will provide you reasonable notice of any such changes by posting the new prices on the Site and by sending you email notification. If you do not wish to pay the new prices, you may cancel the services prior to the change going into effect.</p>
    </li>
    <li style="outline: none: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding: 20px 0px 10px: ">
        <h3 style="outline: none: margin: 0px 0px 5px: font-size: 18px: ">11. Termination</h3>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">Either party may terminate the Services at any time by notifying the other party by any means. 69CUK, Inc may also terminate or suspend any and all Services and access to the Site immediately, without prior notice or liability, if Subscriber breaches any of the terms or conditions of this Agreement. Upon termination of Subscribers account, Subscriber right to use the Services, access the Site, and any Content will immediately cease. All provisions of this Agreement which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, and limitations of liability. Termination of Your access to and use of the Site and the Services shall not relieve Subscriber of any obligations arising or accruing prior to such termination or limit any liability which Subscriber otherwise may have to 69CUK, Inc or the Site, including without limitation any indemnification obligations contained herein.</p>
    </li>
    <li style="outline: none: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding: 20px 0px 10px: ">
        <h3 style="outline: none: margin: 0px 0px 5px: font-size: 18px: ">12. Privacy</h3>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">Please review our<a href="/privacy" style="outline: none: color: rgb(0, 165, 240): text-decoration: none: -webkit-transition: color 0.2s linear: "> <font color="black"><b>Privacy Policy</b></font></a>, which governs the use of personal information on the Site and to which Subscriber agrees to be bound as a user of the Site.</p>
    </li>
    <li style="outline: none: border-bottom-width: 1px: border-bottom-style: solid: border-bottom-color: rgb(221, 221, 221): padding: 20px 0px 10px: ">
        <h3 style="outline: none: margin: 0px 0px 5px: font-size: 18px: ">13. Miscellaneous</h3>
        <p style="outline: none: font-size: 12px: line-height: 1.5em: margin: 0px 0px 10px: ">This Agreement (including the Privacy Policy), as modified from time to time, constitutes the entire agreement between You, the Site and 69CUK, Inc with respect to the subject matter hereof. This Agreement replaces all prior or contemporaneous understandings or agreements, written or oral, regarding the subject matter hereof. The failure of either party to exercise in any respect any right provided for herein shall not be deemed a waiver of any further rights hereunder. 69CUK, Inc shall not be liable for any failure to perform its obligations hereunder where such failure results from any cause beyond 69CUK, Inc reasonable control, including, without limitation, mechanical, electronic or.96.ltmunications failure or degradation. If any provision of this Agreement is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary so that this Agreement shall otherwise remain in full force and effect and enforceable. This Agreement is not assignable, transferable or sublicensable by Subscriber except with 69CUK, Inc prior written consent. 69CUK, Inc may assign this Agreement in whole or in part at any time without Subscriber consent. This Agreement shall be governed by and construed in accordance with the laws of the state of Delaware without regard to the conflict of laws provisions thereof. No agency, partnership, joint venture, or employment is created as a result of this Agreement and Subscriber does not have any authority of any kind to bind 69CUK, Inc in any respect whatsoever.</p>
    </li>
</ul>
<p></p>
</div>
@endsection